/* ============================================================
   THE SIGNAL — Daily Signal Email Dispatch
   Native Netlify Scheduled Function

   Reads the latest brief generated by the daily-content-agent
   (data/latest-daily-signal.json) and dispatches it as a Resend
   broadcast to the "The Signal — Newsletter" segment. Resend's broadcast
   endpoints don't support an Idempotency-Key, so an atomic per-date claim in
   Netlify Blobs (see resolveDispatchPlan below) does that job instead: it
   stops a double cron fire, a manual trigger landing the same day as the
   scheduled run, or a retried invocation from sending the newsletter twice
   — including two truly concurrent invocations, via Blobs' conditional
   "only if new" write, and a crash between creating and sending a broadcast,
   by resuming the send step on the existing broadcastId rather than
   creating a second one. It fails CLOSED: if the dispatch log can't be
   read/written, the tick is skipped rather than risking a duplicate send —
   a skipped day is cheap and visible; a duplicate send to the whole list is
   not.

   Triggers:
   - Scheduled: runs on the cron declared in netlify.toml under
     [functions."send-signal"] (default: daily at 12:00 UTC).
   - Manual:    POST /api/send-signal with header
     `Authorization: ******`
     (handy for the GitHub Actions content workflow to ping
     immediately after publishing.)

   Required Netlify env vars (Site settings → Environment):
     RESEND_API_KEY          — sending-scoped Resend API key (domain:
                                1commercesolutions.com)
     RESEND_SIGNAL_SEGMENT_ID — Resend segment ID for "The Signal — Newsletter"
   Optional:
     SIGNAL_FROM_EMAIL       — default: signal@1commercesolutions.com
                                (must be a verified-sending domain in Resend —
                                1commerce.online is NOT verified there)
     SIGNAL_FROM_NAME        — default: The Signal
     SIGNAL_DISPATCH_TOKEN   — shared secret for manual POSTs
     SIGNAL_SITE_URL         — default: https://1commercesolutions.com

   With no RESEND_API_KEY/RESEND_SIGNAL_SEGMENT_ID set, the function
   logs the payload it WOULD send and returns 200 so the schedule
   keeps running without paging on every cron tick.
   ============================================================ */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Constant-time string comparison. Returns false on any length mismatch so
// timingSafeEqual never throws on differing buffer lengths.
function safeEqual(a, b) {
  const bufA = Buffer.from(String(a), 'utf8');
  const bufB = Buffer.from(String(b), 'utf8');
  if (bufA.length !== bufB.length) return false;
  return crypto.timingSafeEqual(bufA, bufB);
}

const SITE_URL = process.env.SIGNAL_SITE_URL || 'https://1commercesolutions.com';
const FROM_EMAIL = process.env.SIGNAL_FROM_EMAIL || 'signal@1commercesolutions.com';
const FROM_NAME = process.env.SIGNAL_FROM_NAME || 'The Signal';
const RESEND_API = 'https://api.resend.com';

exports.handler = async (event) => {
  const isScheduled = !!(event && event.headers && (event.headers['x-nf-event'] === 'schedule' || event.headers['X-Nf-Event'] === 'schedule'));

  // Manual HTTP trigger requires a bearer token. Scheduled invocations skip auth.
  if (!isScheduled) {
    if (event.httpMethod && event.httpMethod !== 'POST') {
      return json(405, { error: 'Method not allowed' });
    }
    const token = process.env.SIGNAL_DISPATCH_TOKEN;
    const auth = (event.headers && (event.headers.authorization || event.headers.Authorization)) || '';
    if (!token || !safeEqual(auth, 'Bearer ' + token)) {
      return json(401, { error: 'Unauthorized' });
    }
  }

  let brief;
  try {
    brief = loadLatestBrief();
  } catch (err) {
    console.error('send-signal: failed to load latest brief —', err.message);
    return json(500, { error: 'Failed to load latest Signal brief' });
  }

  const subject = brief.title || ('The Signal — ' + brief.date);
  const previewText = brief.thesis || '';
  const html = renderHtml(brief);
  const text = renderText(brief);

  const apiKey = process.env.RESEND_API_KEY;
  const segmentId = process.env.RESEND_SIGNAL_SEGMENT_ID;

  if (!apiKey || !segmentId) {
    console.warn('send-signal: RESEND_API_KEY/RESEND_SIGNAL_SEGMENT_ID not configured — logging only.');
    console.log('send-signal: would dispatch', { date: brief.date, subject, htmlBytes: html.length, textBytes: text.length });
    return json(200, { ok: true, dispatched: false, reason: 'Resend env vars not set; payload logged.' });
  }

  // Claim this date before touching Resend at all — see the header comment
  // and resolveDispatchPlan for why this has to be atomic, not read-then-write.
  let plan;
  try {
    plan = await resolveDispatchPlan(brief.date);
  } catch (err) {
    console.warn('send-signal: dispatch-log unavailable, skipping this tick for safety —', err && err.message);
    return json(200, { ok: true, dispatched: false, reason: 'Dispatch log unavailable; skipped for safety.' });
  }
  if (plan.action === 'skip') {
    console.log('send-signal: already dispatched for', brief.date, '— skipping duplicate send.');
    return json(200, { ok: true, dispatched: false, reason: 'Already dispatched for ' + brief.date + '.' });
  }
  if (plan.action === 'wait') {
    console.log('send-signal: dispatch already in progress for', brief.date, '— skipping.');
    return json(200, { ok: true, dispatched: false, reason: 'Dispatch already in progress for ' + brief.date + '.' });
  }

  let broadcastId = plan.broadcastId || null;
  try {
    if (!broadcastId) {
      broadcastId = await createBroadcast({
        apiKey,
        segmentId,
        subject,
        previewText,
        html,
        text,
        name: 'The Signal — ' + brief.date,
      });
      // Record the id before attempting the send, so a crash between the two
      // Resend calls resumes at 'resume' next time instead of re-creating.
      await plan.store.setJSON(brief.date, { status: 'claimed', broadcastId, claimedAt: new Date().toISOString() });
    }
    await sendBroadcast({ apiKey, broadcastId });
    await plan.store.setJSON(brief.date, { status: 'sent', broadcastId, dispatchedAt: new Date().toISOString() });
    console.log('send-signal: dispatched broadcast', broadcastId, 'for', brief.date);
    return json(200, { ok: true, dispatched: true, broadcastId, date: brief.date });
  } catch (err) {
    if (!broadcastId) {
      // Nothing was created at Resend yet — safe to release the claim so the
      // next invocation gets a clean retry instead of waiting on a dead claim.
      await plan.store.delete(brief.date).catch(() => {});
    }
    // If a broadcastId does exist, deliberately leave the {status:'claimed',
    // broadcastId} record in place — the next invocation's resolveDispatchPlan
    // resumes by retrying only the send step, instead of creating a second
    // broadcast for the same brief.
    console.error('send-signal: Resend dispatch failed —', err.message);
    return json(502, { error: 'Resend dispatch failed', detail: err.message });
  }
};

function loadLatestBrief() {
  // `data/latest-daily-signal.json` is bundled via `included_files`
  // in netlify.toml so it ships with the function deploy.
  const candidates = [
    path.join(process.cwd(), 'data', 'latest-daily-signal.json'),
    path.resolve(__dirname, '..', 'data', 'latest-daily-signal.json'),
    path.resolve(__dirname, '..', '..', 'data', 'latest-daily-signal.json'),
  ];
  for (const file of candidates) {
    if (fs.existsSync(file)) {
      return JSON.parse(fs.readFileSync(file, 'utf8'));
    }
  }
  throw new Error('latest-daily-signal.json not found (checked: ' + candidates.join(', ') + ')');
}

// Per-date dispatch state in Netlify Blobs. `@netlify/blobs` is dependency-
// declared but this file is CommonJS, so it's loaded via dynamic import
// rather than `require()`.
async function getDispatchStore() {
  const { getStore } = await import('@netlify/blobs');
  return getStore('signal-dispatch-log');
}

// Claims `date` for this invocation, or reports what an earlier one already
// did — this is the actual concurrency guard, not just a courtesy check:
//   { action: 'send' }                — no prior record; this call owns it
//   { action: 'skip' }                — already fully sent
//   { action: 'resume', broadcastId } — broadcast was created but the send
//                                        step never confirmed; retry only
//                                        that step, on the same broadcastId
//   { action: 'wait' }                — claimed moments ago by another
//                                        invocation (or a crash before it
//                                        even got a broadcastId); do nothing
// `onlyIfNew` is an atomic conditional write — the primitive that makes this
// safe against two truly concurrent invocations, unlike a plain read-then-
// write check.
const STALE_CLAIM_MS = 5 * 60 * 1000;

async function resolveDispatchPlan(date) {
  const store = await getDispatchStore();
  const claim = { status: 'claimed', claimedAt: new Date().toISOString() };
  const { modified } = await store.setJSON(date, claim, { onlyIfNew: true });
  if (modified) return { action: 'send', store };

  const existing = await store.get(date, { type: 'json' });
  if (!existing) return { action: 'send', store }; // cleared between the two calls above; safe to proceed
  if (existing.status === 'sent') return { action: 'skip', store };
  if (existing.broadcastId) return { action: 'resume', broadcastId: existing.broadcastId, store };

  const claimedAgoMs = Date.now() - new Date(existing.claimedAt || 0).getTime();
  if (claimedAgoMs > STALE_CLAIM_MS) {
    // Abandoned claim — crashed before createBroadcast even returned an id.
    // Comfortably longer than any realistic Resend round-trip, so safe to take over.
    await store.setJSON(date, claim);
    return { action: 'send', store };
  }
  return { action: 'wait', store };
}

async function createBroadcast({ apiKey, segmentId, subject, previewText, html, text, name }) {
  const res = await fetch(RESEND_API + '/broadcasts', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + apiKey,
    },
    body: JSON.stringify({
      segment_id: segmentId,
      from: FROM_NAME + ' <' + FROM_EMAIL + '>',
      subject,
      preview_text: previewText,
      html,
      text,
      name,
    }),
  });
  if (!res.ok) {
    throw new Error('create broadcast ' + res.status + ' ' + (await safeText(res)));
  }
  const body = await res.json();
  if (!body || !body.id) throw new Error('create broadcast: missing id in response');
  return body.id;
}

async function sendBroadcast({ apiKey, broadcastId }) {
  const res = await fetch(RESEND_API + '/broadcasts/' + encodeURIComponent(broadcastId) + '/send', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + apiKey,
    },
    body: JSON.stringify({}),
  });
  if (!res.ok) {
    throw new Error('send broadcast ' + res.status + ' ' + (await safeText(res)));
  }
}

async function safeText(res) {
  try { return await res.text(); } catch (_) { return ''; }
}

function renderText(brief) {
  const lines = [];
  lines.push((brief.title || 'The Signal') + ' — ' + brief.date);
  lines.push('');
  if (brief.thesis) { lines.push(brief.thesis); lines.push(''); }
  if (Array.isArray(brief.takeaways) && brief.takeaways.length) {
    lines.push('TAKEAWAYS');
    brief.takeaways.forEach((t) => lines.push('  - ' + t));
    lines.push('');
  }
  if (Array.isArray(brief.sections)) {
    brief.sections.forEach((s) => {
      lines.push((s.heading || '').toUpperCase());
      lines.push(s.body || '');
      lines.push('');
    });
  }
  if (Array.isArray(brief.prompts) && brief.prompts.length) {
    lines.push('OPERATOR PROMPTS');
    brief.prompts.forEach((p) => lines.push('  ? ' + p));
    lines.push('');
  }
  lines.push('Read the full dispatch: ' + SITE_URL + '/daily/' + brief.date + '.html');
  lines.push('');
  lines.push('You are subscribed to ' + FROM_NAME + ' at ' + SITE_URL + '.');
  lines.push('Unsubscribe: {{{RESEND_UNSUBSCRIBE_URL}}}');
  return lines.join('\n');
}

// Dark/amber "dossier" theme matching the site's design tokens (style.css
// :root and functions/confirm.mjs). Table-based layout with inline styles
// and bgcolor attributes throughout — required for Outlook/Gmail rendering
// and for the Resend broadcast HTML pipeline.
const FONT_MONO = "'JetBrains Mono',ui-monospace,Consolas,monospace";
const FONT_SERIF = "'Fraunces',Georgia,serif";
const FONT_SANS = "'IBM Plex Sans',Arial,Helvetica,sans-serif";
const COLOR_BG = '#0B0E13';
const COLOR_CARD = '#11151d';
const COLOR_BORDER = '#232a36';
const COLOR_TEXT = '#E7EAF0';
const COLOR_BODY = '#C7CCD6';
const COLOR_MUTED = '#9AA2AE';
const COLOR_FAINT = '#6E7891';
const COLOR_AMBER = '#E8B86A';

function renderHtml(brief) {
  const permalink = SITE_URL + '/daily/' + encodeURIComponent(brief.date) + '.html';

  const takeaways = (brief.takeaways || []).map((t) => (
    '<tr><td style="font-family:' + FONT_SANS + ';font-size:15px;line-height:1.7;color:' + COLOR_TEXT + ';padding:0 0 8px 0;">— ' + escapeHtml(t) + '</td></tr>'
  )).join('');

  const sections = (brief.sections || []).map((s) => (
    '<tr><td style="padding:0 0 24px 0;">' +
      '<h2 style="margin:0 0 8px 0;font-family:' + FONT_SERIF + ';font-size:18px;line-height:1.3;font-weight:600;color:' + COLOR_TEXT + ';">' + escapeHtml(s.heading || '') + '</h2>' +
      '<p style="margin:0;font-family:' + FONT_SANS + ';font-size:15px;line-height:1.7;color:' + COLOR_BODY + ';">' + escapeHtml(s.body || '') + '</p>' +
    '</td></tr>'
  )).join('');

  const prompts = (brief.prompts || []).map((p) => (
    '<tr><td style="font-family:' + FONT_SANS + ';font-size:14px;line-height:1.6;color:' + COLOR_MUTED + ';padding:0 0 8px 0;">? ' + escapeHtml(p) + '</td></tr>'
  )).join('');

  return [
    '<!doctype html>',
    '<html lang="en"><head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<meta http-equiv="X-UA-Compatible" content="IE=edge">',
    '<title>' + escapeHtml(brief.title || 'The Signal') + '</title>',
    '</head>',
    '<body style="margin:0;padding:0;background-color:' + COLOR_BG + ';">',
    '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="' + COLOR_BG + '" style="background-color:' + COLOR_BG + ';"><tr><td align="center" style="padding:32px 16px;">',
    '<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" bgcolor="' + COLOR_CARD + '" style="max-width:600px;width:100%;background-color:' + COLOR_CARD + ';border:1px solid ' + COLOR_BORDER + ';border-radius:14px;">',

    '<tr><td style="padding:36px 36px 4px 36px;">',
    '<p style="margin:0 0 14px 0;font-family:' + FONT_MONO + ';font-size:12px;line-height:1.2;letter-spacing:2px;text-transform:uppercase;color:' + COLOR_AMBER + ';">&#9670; ' + escapeHtml(FROM_NAME.toUpperCase()) + ' &middot; ' + escapeHtml(brief.date) + '</p>',
    '<h1 style="margin:0 0 14px 0;font-family:' + FONT_SERIF + ';font-size:26px;line-height:1.3;font-weight:600;color:' + COLOR_TEXT + ';">' + escapeHtml(brief.title || 'The Signal') + '</h1>',
    brief.thesis ? '<p style="margin:0 0 8px 0;font-family:' + FONT_SANS + ';font-size:17px;line-height:1.6;color:' + COLOR_BODY + ';">' + escapeHtml(brief.thesis) + '</p>' : '',
    '</td></tr>',

    takeaways ? (
      '<tr><td style="padding:8px 36px 20px 36px;">' +
      '<p style="margin:0 0 10px 0;font-family:' + FONT_MONO + ';font-size:12px;letter-spacing:1.5px;text-transform:uppercase;color:' + COLOR_MUTED + ';">Takeaways</p>' +
      '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">' + takeaways + '</table>' +
      '</td></tr>'
    ) : '',

    sections ? '<tr><td style="padding:12px 36px 0 36px;border-top:1px solid ' + COLOR_BORDER + ';"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-top:20px;">' + sections + '</table></td></tr>' : '',

    prompts ? (
      '<tr><td style="padding:0 36px 24px 36px;">' +
      '<p style="margin:0 0 10px 0;font-family:' + FONT_MONO + ';font-size:12px;letter-spacing:1.5px;text-transform:uppercase;color:' + COLOR_MUTED + ';">Operator prompts</p>' +
      '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">' + prompts + '</table>' +
      '</td></tr>'
    ) : '',

    '<tr><td style="padding:8px 36px 32px 36px;border-top:1px solid ' + COLOR_BORDER + ';">' +
    '<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin-top:20px;"><tr><td bgcolor="' + COLOR_AMBER + '" style="background-color:' + COLOR_AMBER + ';border-radius:8px;">' +
    '<a href="' + escapeAttr(permalink) + '" style="display:inline-block;padding:12px 22px;font-family:' + FONT_SANS + ';font-size:14px;font-weight:600;color:' + COLOR_BG + ';text-decoration:none;">Read the full dispatch &rarr;</a>' +
    '</td></tr></table>' +
    '</td></tr>',

    '<tr><td style="padding:0 36px 32px 36px;">' +
    '<p style="margin:0;font-family:' + FONT_SANS + ';font-size:12px;line-height:1.6;color:' + COLOR_FAINT + ';">You\'re subscribed to ' + escapeHtml(FROM_NAME) + ' at ' + escapeHtml(SITE_URL.replace(/^https?:\/\//, '')) + '. <a href="{{{RESEND_UNSUBSCRIBE_URL}}}" style="color:' + COLOR_MUTED + ';">Unsubscribe</a></p>' +
    '</td></tr>',

    '</table>',
    '</td></tr></table>',
    '</body></html>',
  ].join('');
}

function escapeHtml(str) {
  return String(str == null ? '' : str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(str) {
  return escapeHtml(str);
}

function json(statusCode, body) {
  return {
    statusCode,
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  };
}
