/* ============================================================
   THE SIGNAL — Daily Signal Email Dispatch
   Native Netlify Scheduled Function

   Reads the latest brief generated by the daily-content-agent
   (data/latest-daily-signal.json) and dispatches it as an
   email campaign to the existing MailerLite subscriber list.

   Triggers:
   - Scheduled: runs on the cron declared in netlify.toml under
     [functions."send-signal"] (default: daily at 12:00 UTC).
   - Manual:    POST /api/send-signal with header
     `Authorization: ******`
     (handy for the GitHub Actions content workflow to ping
     immediately after publishing.)

   Required Netlify env vars (Site settings → Environment):
     MAILERLITE_API_KEY      — Connect API token from MailerLite
     MAILERLITE_GROUP_ID     — group/segment ID to send to
   Optional:
     SIGNAL_FROM_EMAIL       — default: skdev@1commerce.online
     SIGNAL_FROM_NAME        — default: The Signal
     SIGNAL_DISPATCH_TOKEN   — shared secret for manual POSTs
     SIGNAL_SITE_URL         — default: https://1commercesolutions.com

   With no MAILERLITE_API_KEY set, the function logs the
   payload it WOULD send and returns 200 so the schedule
   keeps running without paging on every cron tick.
   ============================================================ */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Constant-time string comparison. Returns false on any length mismatch so
// timingSafeEqual never throws on differing buffer lengths.
function safeEqual(a, b) {
  const bufA = Buffer.from(String(a), 'utf8');
  const bufB = Buffer.from(String(b), 'utf8');
  if (bufA.length !== bufB.length) return false;
  return crypto.timingSafeEqual(bufA, bufB);
}

const SITE_URL = process.env.SIGNAL_SITE_URL || 'https://1commercesolutions.com';
const FROM_EMAIL = process.env.SIGNAL_FROM_EMAIL || 'skdev@1commerce.online';
const FROM_NAME = process.env.SIGNAL_FROM_NAME || 'The Signal';
const MAILERLITE_API = 'https://connect.mailerlite.com/api';

exports.handler = async (event) => {
  const isScheduled = !!(event && event.headers && (event.headers['x-nf-event'] === 'schedule' || event.headers['X-Nf-Event'] === 'schedule'));

  // Manual HTTP trigger requires a bearer token. Scheduled invocations skip auth.
  if (!isScheduled) {
    if (event.httpMethod && event.httpMethod !== 'POST') {
      return json(405, { error: 'Method not allowed' });
    }
    const token = process.env.SIGNAL_DISPATCH_TOKEN;
    const auth = (event.headers && (event.headers.authorization || event.headers.Authorization)) || '';
    if (!token || !safeEqual(auth, 'Bearer ' + token)) {
      return json(401, { error: 'Unauthorized' });
    }
  }

  let brief;
  try {
    brief = loadLatestBrief();
  } catch (err) {
    console.error('send-signal: failed to load latest brief —', err.message);
    return json(500, { error: 'Failed to load latest Signal brief' });
  }

  const subject = brief.title || ('The Signal — ' + brief.date);
  const html = renderHtml(brief);
  const text = renderText(brief);

  const apiKey = process.env.MAILERLITE_API_KEY;
  const groupId = process.env.MAILERLITE_GROUP_ID;

  if (!apiKey || !groupId) {
    console.warn('send-signal: MAILERLITE_API_KEY/MAILERLITE_GROUP_ID not configured — logging only.');
    console.log('send-signal: would dispatch', { date: brief.date, subject, htmlBytes: html.length, textBytes: text.length });
    return json(200, { ok: true, dispatched: false, reason: 'MailerLite env vars not set; payload logged.' });
  }

  try {
    const campaignId = await createCampaign({ apiKey, groupId, subject, html, plain: text });
    await scheduleCampaign({ apiKey, campaignId });
    console.log('send-signal: dispatched campaign', campaignId, 'for', brief.date);
    return json(200, { ok: true, dispatched: true, campaignId, date: brief.date });
  } catch (err) {
    console.error('send-signal: MailerLite dispatch failed —', err.message);
    return json(502, { error: 'MailerLite dispatch failed', detail: err.message });
  }
};

function loadLatestBrief() {
  // `data/latest-daily-signal.json` is bundled via `included_files`
  // in netlify.toml so it ships with the function deploy.
  const candidates = [
    path.join(process.cwd(), 'data', 'latest-daily-signal.json'),
    path.resolve(__dirname, '..', 'data', 'latest-daily-signal.json'),
    path.resolve(__dirname, '..', '..', 'data', 'latest-daily-signal.json'),
  ];
  for (const file of candidates) {
    if (fs.existsSync(file)) {
      return JSON.parse(fs.readFileSync(file, 'utf8'));
    }
  }
  throw new Error('latest-daily-signal.json not found (checked: ' + candidates.join(', ') + ')');
}

async function createCampaign({ apiKey, groupId, subject, html, plain }) {
  const res = await fetch(MAILERLITE_API + '/campaigns', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'Authorization': 'Bearer ' + apiKey,
    },
    body: JSON.stringify({
      name: subject,
      type: 'regular',
      emails: [
        {
          subject,
          from_name: FROM_NAME,
          from: FROM_EMAIL,
          content: html,
          plain_text: plain,
        },
      ],
      groups: [String(groupId)],
    }),
  });
  if (!res.ok) {
    throw new Error('create campaign ' + res.status + ' ' + (await safeText(res)));
  }
  const body = await res.json();
  const id = body && body.data && body.data.id;
  if (!id) throw new Error('create campaign: missing id in response');
  return id;
}

async function scheduleCampaign({ apiKey, campaignId }) {
  const res = await fetch(MAILERLITE_API + '/campaigns/' + encodeURIComponent(campaignId) + '/schedule', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'Authorization': 'Bearer ' + apiKey,
    },
    body: JSON.stringify({ delivery: 'instant' }),
  });
  if (!res.ok) {
    throw new Error('schedule campaign ' + res.status + ' ' + (await safeText(res)));
  }
}

async function safeText(res) {
  try { return await res.text(); } catch (_) { return ''; }
}

function renderText(brief) {
  const lines = [];
  lines.push((brief.title || 'The Signal') + ' — ' + brief.date);
  lines.push('');
  if (brief.thesis) { lines.push(brief.thesis); lines.push(''); }
  if (Array.isArray(brief.takeaways) && brief.takeaways.length) {
    lines.push('Takeaways:');
    brief.takeaways.forEach((t) => lines.push('  • ' + t));
    lines.push('');
  }
  if (Array.isArray(brief.sections)) {
    brief.sections.forEach((s) => {
      lines.push(s.heading);
      lines.push('—'.repeat(Math.min(60, (s.heading || '').length || 3)));
      lines.push(s.body);
      lines.push('');
    });
  }
  if (Array.isArray(brief.prompts) && brief.prompts.length) {
    lines.push('Operator prompts:');
    brief.prompts.forEach((p) => lines.push('  ? ' + p));
    lines.push('');
  }
  lines.push('Read on the site: ' + SITE_URL + '/daily/' + brief.date + '.html');
  lines.push('');
  lines.push('— ' + FROM_NAME);
  return lines.join('\n');
}

function renderHtml(brief) {
  const takeaways = (brief.takeaways || []).map((t) => '<li>' + escapeHtml(t) + '</li>').join('');
  const sections = (brief.sections || []).map((s) => (
    '<section style="margin:0 0 28px 0;">' +
      '<h2 style="font:600 18px/1.3 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0 0 8px 0;color:#111;">' +
      escapeHtml(s.heading || '') + '</h2>' +
      '<p style="font:400 16px/1.6 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;color:#222;">' +
      escapeHtml(s.body || '') + '</p>' +
    '</section>'
  )).join('');
  const prompts = (brief.prompts || []).map((p) => '<li style="margin:0 0 6px 0;">' + escapeHtml(p) + '</li>').join('');
  const permalink = SITE_URL + '/daily/' + encodeURIComponent(brief.date) + '.html';

  return [
    '<!doctype html>',
    '<html><head><meta charset="utf-8"><title>', escapeHtml(brief.title || 'The Signal'), '</title></head>',
    '<body style="margin:0;padding:24px;background:#f7f7f5;">',
      '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;margin:0 auto;background:#fff;border:1px solid #e5e5e2;">',
        '<tr><td style="padding:32px 32px 8px 32px;">',
          '<p style="font:600 12px/1.2 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;letter-spacing:0.12em;text-transform:uppercase;color:#888;margin:0 0 8px 0;">The Signal · ', escapeHtml(brief.date), '</p>',
          '<h1 style="font:700 26px/1.25 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0 0 12px 0;color:#111;">', escapeHtml(brief.title || 'The Signal'), '</h1>',
          brief.thesis ? '<p style="font:400 17px/1.55 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#333;margin:0 0 16px 0;">' + escapeHtml(brief.thesis) + '</p>' : '',
        '</td></tr>',
        takeaways ? '<tr><td style="padding:0 32px 16px 32px;"><h2 style="font:600 14px/1.2 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;letter-spacing:0.08em;text-transform:uppercase;color:#666;margin:0 0 8px 0;">Takeaways</h2><ul style="font:400 16px/1.6 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#222;margin:0;padding:0 0 0 20px;">' + takeaways + '</ul></td></tr>' : '',
        '<tr><td style="padding:16px 32px 8px 32px;">', sections, '</td></tr>',
        prompts ? '<tr><td style="padding:0 32px 16px 32px;"><h2 style="font:600 14px/1.2 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;letter-spacing:0.08em;text-transform:uppercase;color:#666;margin:0 0 8px 0;">Operator prompts</h2><ul style="font:400 16px/1.6 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#222;margin:0;padding:0 0 0 20px;">' + prompts + '</ul></td></tr>' : '',
        '<tr><td style="padding:8px 32px 32px 32px;border-top:1px solid #eee;">',
          '<p style="font:400 14px/1.5 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#555;margin:0 0 8px 0;">Read this dispatch on the site:</p>',
          '<p style="font:600 14px/1.5 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;"><a href="', escapeAttr(permalink), '" style="color:#111;">', escapeHtml(permalink), '</a></p>',
        '</td></tr>',
      '</table>',
      '<p style="max-width:640px;margin:16px auto 0 auto;font:400 12px/1.5 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#888;text-align:center;">You subscribed to The Signal at ', escapeHtml(SITE_URL), '. {$unsubscribe}</p>',
    '</body></html>',
  ].join('');
}

function escapeHtml(str) {
  return String(str == null ? '' : str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(str) {
  return escapeHtml(str);
}

function json(statusCode, body) {
  return {
    statusCode,
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  };
}
