// Topic queue for the daily archive transmission agent.
//
// This is deliberately long. The daily brief generator failed because it cycled
// seven themes with `topics[day % 7]`, so every theme accumulated ~8 pages that
// competed with each other. Here each topic is consumed once and recorded in
// data/archive-state.json, so a topic never repeats. When the queue runs low
// the agent warns loudly rather than wrapping around.
//
// Each entry is one distinct search intent. Keep `keyword` unique across the
// file — the agent refuses to publish a topic whose keyword already appears on
// an indexed page.

export const archiveTopics = [
  { id: 'headless-migration-cost', keyword: 'headless commerce migration cost', title: 'What a Headless Commerce Migration Actually Costs', angle: 'The line items nobody quotes: content modelling, preview infrastructure, and the six months of dual-running.' },
  { id: 'shopify-app-vs-custom', keyword: 'shopify app vs custom build', title: 'When to Buy the Shopify App and When to Build It Yourself', angle: 'A decision rule based on how close the feature sits to your actual differentiation.' },
  { id: 'checkout-abandonment-diagnosis', keyword: 'diagnose checkout abandonment', title: 'Diagnosing Checkout Abandonment Without Guessing', angle: 'Reading the funnel by step rather than treating abandonment as one number.' },
  { id: 'product-data-model', keyword: 'ecommerce product data model', title: 'The Product Data Model That Survives Your Third Catalog Change', angle: 'Why variant modelling decisions made in week one determine what you can sell in year two.' },
  { id: 'inventory-sync-failures', keyword: 'inventory sync failure modes', title: 'Inventory Sync Failure Modes and How to Catch Them Early', angle: 'Overselling is a distributed systems problem wearing a retail costume.' },
  { id: 'returns-as-signal', keyword: 'ecommerce returns data', title: 'Returns Are Product Feedback With a Shipping Label', angle: 'Turning return reasons into a prioritized fix list instead of a cost line.' },
  { id: 'email-deliverability-basics', keyword: 'transactional email deliverability', title: 'Transactional Email Deliverability for Operators', angle: 'The DNS records, warming discipline, and content rules that decide whether receipts arrive.' },
  { id: 'pricing-experiment-design', keyword: 'pricing experiment design', title: 'Designing a Pricing Experiment You Can Actually Read', angle: 'Why most price tests measure noise, and what a readable one requires.' },
  { id: 'subscription-churn-anatomy', keyword: 'subscription churn analysis', title: 'The Anatomy of Subscription Churn', angle: 'Separating involuntary churn, early churn, and genuine dissatisfaction — three problems with three fixes.' },
  { id: 'marketplace-vs-direct', keyword: 'marketplace vs direct to consumer', title: 'Marketplace or Direct: Choosing Where Your Margin Lives', angle: 'The trade between acquisition cost and customer ownership, quantified.' },
  { id: 'saas-onboarding-friction', keyword: 'reduce saas onboarding friction', title: 'Onboarding Friction Is Usually a Data Problem', angle: 'Users stall where your product asks for something they do not have yet.' },
  { id: 'internal-tools-buy-build', keyword: 'internal tools build or buy', title: 'Internal Tools: The Build-or-Buy Line for Small Teams', angle: 'A rule based on how often the workflow changes, not how much the tool costs.' },
  { id: 'observability-for-small-teams', keyword: 'observability for small teams', title: 'Observability When You Have No On-Call Rotation', angle: 'What to instrument first when nobody is awake at 3am to look at it.' },
  { id: 'error-budget-solo', keyword: 'error budget solo founder', title: 'Error Budgets for Operations of One', angle: 'Deciding in advance how much breakage is acceptable, so you stop firefighting everything.' },
  { id: 'database-migration-safety', keyword: 'zero downtime database migration', title: 'Running a Database Migration Without Taking the Store Down', angle: 'Expand, backfill, contract — and the checkpoints between each phase.' },
  { id: 'feature-flag-discipline', keyword: 'feature flag hygiene', title: 'Feature Flags Rot If You Do Not Delete Them', angle: 'The maintenance cost nobody budgets for, and the removal policy that fixes it.' },
  { id: 'api-versioning-strategy', keyword: 'api versioning strategy', title: 'Versioning an API You Will Have to Support for Years', angle: 'Choosing a compatibility promise before your first external integration.' },
  { id: 'webhook-reliability', keyword: 'reliable webhook processing', title: 'Webhooks Will Arrive Twice, Late, or Not at All', angle: 'Idempotency keys, replay handling, and the dead letter queue you will need.' },
  { id: 'rate-limit-design', keyword: 'api rate limiting design', title: 'Rate Limiting That Protects You Without Punishing Customers', angle: 'Picking limits from real usage distributions instead of round numbers.' },
  { id: 'caching-invalidation-commerce', keyword: 'cache invalidation ecommerce', title: 'Cache Invalidation on a Storefront That Changes Hourly', angle: 'Where stale data is free, where it costs a sale, and how to tell the two apart.' },
  { id: 'search-relevance-tuning', keyword: 'ecommerce search relevance', title: 'Tuning Storefront Search When Nobody Finds Anything', angle: 'Zero-result queries are your highest-signal, least-read report.' },
  { id: 'recommendation-without-ml', keyword: 'product recommendations without machine learning', title: 'Product Recommendations Before You Deserve Machine Learning', angle: 'Rules that beat a cold-start model, and when to graduate.' },
  { id: 'personalization-limits', keyword: 'ecommerce personalization limits', title: 'The Point Where Personalization Starts Costing You Sales', angle: 'Narrowing the visible catalog is a decision, not a neutral optimization.' },
  { id: 'attribution-honesty', keyword: 'marketing attribution accuracy', title: 'Attribution Is a Model, Not a Measurement', angle: 'Using it to make relative decisions without believing the absolute numbers.' },
  { id: 'ltv-estimation', keyword: 'customer lifetime value calculation', title: 'Estimating Lifetime Value Without Fooling Yourself', angle: 'Cohort curves, survivorship bias, and why your LTV is probably too high.' },
  { id: 'cac-payback-discipline', keyword: 'cac payback period', title: 'CAC Payback Is the Only Growth Metric That Constrains You', angle: 'Why the payback window, not the ratio, determines how fast you can spend.' },
  { id: 'content-that-converts', keyword: 'content marketing for ecommerce', title: 'Content That Sells Without Pretending to Be an Article', angle: 'Matching page format to where the reader sits in the buying decision.' },
  { id: 'programmatic-seo-risk', keyword: 'programmatic seo risks', title: 'Programmatic SEO and the Thin Content Cliff', angle: 'The point where generated pages stop helping and start suppressing the site.' },
  { id: 'internal-linking-architecture', keyword: 'internal linking structure', title: 'Internal Linking as Site Architecture, Not Decoration', angle: 'Designing the link graph so authority reaches the pages that convert.' },
  { id: 'schema-markup-payoff', keyword: 'structured data seo benefit', title: 'Which Structured Data Actually Changes Anything', angle: 'Separating schema that earns result features from schema that earns nothing.' },
  { id: 'core-web-vitals-reality', keyword: 'core web vitals ecommerce', title: 'Core Web Vitals: What Moves Revenue and What Moves a Score', angle: 'Optimizing the metrics customers feel rather than the ones a tool reports.' },
  { id: 'image-pipeline-cost', keyword: 'ecommerce image optimization', title: 'The Image Pipeline Is Usually Your Whole Performance Problem', angle: 'Formats, sizing, and lazy loading in the order that actually pays.' },
  { id: 'static-vs-dynamic', keyword: 'static site vs dynamic site', title: 'Static Until It Hurts: Choosing Rendering by Failure Mode', angle: 'What each rendering strategy costs you on the worst day, not the average one.' },
  { id: 'serverless-cost-traps', keyword: 'serverless cost traps', title: 'Serverless Bills Are Fine Until One Loop Is Not', angle: 'The invocation patterns that turn a cheap architecture expensive overnight.' },
  { id: 'vendor-lockin-assessment', keyword: 'assessing vendor lock-in', title: 'Pricing Vendor Lock-In Before You Sign', angle: 'Estimating exit cost as a number so it can be weighed like any other.' },
  { id: 'contract-red-flags', keyword: 'saas contract red flags', title: 'Contract Terms That Quietly Cost Operators Money', angle: 'Auto-renewal windows, data portability, and usage definitions worth reading.' },
  { id: 'client-scope-control', keyword: 'controlling project scope creep', title: 'Scope Control for People Who Hate Confrontation', angle: 'Structuring the agreement so boundaries hold without a difficult conversation.' },
  { id: 'pricing-services-value', keyword: 'pricing consulting services', title: 'Pricing Services When You Are the Whole Company', angle: 'Moving from hourly to outcome pricing without losing the deals you need.' },
  { id: 'proposal-that-closes', keyword: 'writing a project proposal', title: 'The Proposal Structure That Removes the Follow-Up Call', angle: 'Answering the four objections a buyer has before they ask them.' },
  { id: 'discovery-call-structure', keyword: 'discovery call framework', title: 'A Discovery Call That Disqualifies Fast', angle: 'Finding the no early is worth more than a full pipeline of maybes.' },
  { id: 'cold-outreach-that-works', keyword: 'cold outreach personalization', title: 'Cold Outreach After Personalization Stopped Working', angle: 'Relevance beats research theatre — and how to demonstrate it in two lines.' },
  { id: 'referral-system-design', keyword: 'referral program design', title: 'Referral Programs Fail on Timing, Not Incentive', angle: 'Asking at the moment of realized value instead of at checkout.' },
  { id: 'community-vs-audience', keyword: 'building a community vs audience', title: 'Audience or Community: They Need Opposite Things From You', angle: 'One scales with your output; the other scales with members talking to each other.' },
  { id: 'newsletter-retention', keyword: 'newsletter retention', title: 'Newsletter Growth Is Retention Wearing a Growth Costume', angle: 'Why open-rate decay is a promise problem, not a subject-line problem.' },
  { id: 'documentation-as-product', keyword: 'documentation as product', title: 'Documentation Is the Cheapest Support Channel You Have', angle: 'Writing for the moment of failure rather than the moment of curiosity.' },
  { id: 'support-macros-quality', keyword: 'customer support macros', title: 'Support Macros That Do Not Sound Like Macros', angle: 'Templating structure while leaving the specific sentence to a human.' },
  { id: 'sla-you-can-keep', keyword: 'setting a realistic sla', title: 'Setting an SLA You Can Keep on a Bad Week', angle: 'Promising against your worst realistic case, not your median one.' },
  { id: 'incident-comms', keyword: 'incident communication', title: 'What to Say While the System Is Still Down', angle: 'A communication template that buys patience instead of spending it.' },
  { id: 'postmortem-culture-solo', keyword: 'writing a postmortem', title: 'Postmortems When the Only Person to Blame Is You', angle: 'Extracting the systemic cause without the ritual of blamelessness theatre.' },
  { id: 'runbook-discipline', keyword: 'writing runbooks', title: 'Runbooks Are for the Version of You That Is Panicking', angle: 'Writing procedures that work at 3am with no context loaded.' },
  { id: 'backup-restore-testing', keyword: 'testing backup restores', title: 'You Do Not Have Backups Until You Have Restored One', angle: 'Making restore drills routine enough that they stop being frightening.' },
  { id: 'security-basics-small', keyword: 'security basics small business', title: 'The Security Work That Matters Before You Have a Security Budget', angle: 'The handful of controls that remove most realistic risk for a small operation.' },
  { id: 'secrets-management', keyword: 'managing api keys safely', title: 'Where Your API Keys Are Right Now', angle: 'Rotating, scoping, and getting credentials out of the places they accumulate.' },
  { id: 'access-offboarding', keyword: 'contractor offboarding checklist', title: 'Offboarding a Contractor Without Leaving Doors Open', angle: 'The access inventory to maintain while people are still onboarding.' },
  { id: 'compliance-without-lawyer', keyword: 'ecommerce compliance basics', title: 'The Compliance Floor for a Small Commerce Operation', angle: 'Privacy policy, data handling, and consent — what is genuinely required.' },
  { id: 'analytics-without-tracking', keyword: 'privacy friendly analytics', title: 'Useful Analytics Without Following People Around', angle: 'The questions you can still answer with aggregate, first-party data.' },
  { id: 'ab-test-sample-size', keyword: 'ab test sample size', title: 'Most A/B Tests on Small Sites Cannot Detect Anything', angle: 'Running the power calculation first, and what to do when the answer is no.' },
  { id: 'qualitative-signal', keyword: 'customer interview technique', title: 'Five Customer Conversations Beat a Survey of Five Hundred', angle: 'Asking about past behaviour instead of future intention.' },
  { id: 'roadmap-under-uncertainty', keyword: 'product roadmap small team', title: 'A Roadmap That Survives Contact With Reality', angle: 'Committing to problems and outcomes rather than dated features.' },
  { id: 'saying-no-to-features', keyword: 'saying no to feature requests', title: 'The Feature Request Backlog Is a Trap', angle: 'Reading requests as evidence about a problem rather than instructions.' },
  { id: 'technical-debt-triage', keyword: 'technical debt prioritization', title: 'Technical Debt Triage by Interest Rate', angle: 'Paying down the debt that compounds, and deliberately keeping the rest.' },
  { id: 'refactor-timing', keyword: 'when to refactor code', title: 'The Right Time to Refactor Is the Third Time It Hurts', angle: 'A trigger rule that prevents both premature abstraction and permanent mess.' },
  { id: 'code-review-solo', keyword: 'code review without a team', title: 'Reviewing Your Own Code Without Lying to Yourself', angle: 'Structural checks that survive the absence of a second reader.' },
  { id: 'testing-what-matters', keyword: 'what to test first', title: 'Testing the Three Paths That Cost Money', angle: 'Coverage targets are noise; failure cost is the useful ranking.' },
  { id: 'ci-that-stays-green', keyword: 'keeping ci green', title: 'A Flaky Test Suite Is Worse Than No Test Suite', angle: 'Because the moment you learn to ignore red, the suite stops working.' },
  { id: 'deploy-confidence', keyword: 'deploy with confidence', title: 'Deploying on Friday Is a Tooling Question', angle: 'What has to be true before the day of the week stops mattering.' },
  { id: 'rollback-strategy', keyword: 'deployment rollback strategy', title: 'Rollback Is a Feature You Have to Build', angle: 'Forward-only migrations, and the recovery plan they force you to design.' },
  { id: 'monorepo-tradeoffs', keyword: 'monorepo vs multiple repos', title: 'One Repo or Many: Choosing by Coordination Cost', angle: 'The answer depends on how often changes cross boundaries.' },
  { id: 'dependency-hygiene', keyword: 'managing dependencies', title: 'Every Dependency Is a Bet on Someone Else Staying Interested', angle: 'Evaluating maintenance risk before adding, and pruning on a schedule.' },
  { id: 'build-times-compound', keyword: 'reducing build times', title: 'Build Time Is a Tax on Every Future Decision', angle: 'Slow feedback changes what you are willing to try, not just how long it takes.' },
  { id: 'local-dev-parity', keyword: 'local development parity', title: 'The Bugs That Only Exist in Production', angle: 'Closing the gap between local and deployed without recreating the cloud.' },
  { id: 'infra-as-code-value', keyword: 'infrastructure as code small team', title: 'Infrastructure as Code When There Is Only One Operator', angle: 'The value is documentation and recovery, not collaboration.' },
  { id: 'cost-monitoring', keyword: 'cloud cost monitoring', title: 'Finding the Line Item That Grew While You Were Not Looking', angle: 'Alerting on cost derivatives rather than reading the bill monthly.' },
  { id: 'multi-region-when', keyword: 'when to go multi region', title: 'You Probably Do Not Need Multi-Region Yet', angle: 'The failure scenarios it actually covers, and their real probability.' },
  { id: 'queue-vs-cron', keyword: 'queue vs cron job', title: 'Cron Jobs Are Queues With Worse Failure Handling', angle: 'When scheduled work should become an actual queue.' },
  { id: 'idempotency-everywhere', keyword: 'idempotency in distributed systems', title: 'Idempotency Is the Cheapest Reliability You Can Buy', angle: 'Designing operations that are safe to run twice, before you need them to be.' },
  { id: 'data-retention-policy', keyword: 'data retention policy', title: 'Keeping Data Forever Is a Decision You Never Made', angle: 'Retention as a deliberate policy with cost, risk, and value weighed.' },
  { id: 'reporting-that-gets-read', keyword: 'internal reporting that gets read', title: 'Reports Nobody Reads Are a Process Failure', angle: 'Designing the number so it changes a decision, or deleting it.' },
  { id: 'dashboard-discipline', keyword: 'dashboard design for operators', title: 'A Dashboard Should Answer One Question', angle: 'Splitting the wall of charts into decisions with owners.' },
  { id: 'forecasting-small-business', keyword: 'small business cash forecasting', title: 'Cash Forecasting When Revenue Is Lumpy', angle: 'Scenario ranges beat a single line when the sample size is small.' },
  { id: 'runway-decisions', keyword: 'managing startup runway', title: 'Runway Math That Changes What You Do This Month', angle: 'Turning a months-remaining number into a decision calendar.' },
  { id: 'hiring-first-person', keyword: 'first hire for solo founder', title: 'The First Hire Is a Bet on Which Constraint Is Real', angle: 'Diagnosing whether you are time-constrained or skill-constrained first.' },
  { id: 'contractor-vs-employee', keyword: 'contractor vs employee tradeoffs', title: 'Contractors Buy Capacity, Employees Buy Context', angle: 'Choosing by how much accumulated knowledge the work requires.' },
  { id: 'delegation-checklist', keyword: 'how to delegate effectively', title: 'Delegation Fails at the Acceptance Criteria', angle: 'What has to be written down before handing work to anyone, human or agent.' },
  { id: 'meeting-replacement', keyword: 'reducing meetings', title: 'Most Meetings Are a Missing Document', angle: 'Identifying which recurring meeting is compensating for absent writing.' },
  { id: 'async-communication', keyword: 'async communication practices', title: 'Async Communication Requires More Structure, Not Less', angle: 'The conventions that make written updates usable without a follow-up call.' },
  { id: 'decision-log', keyword: 'keeping a decision log', title: 'A Decision Log Is Cheaper Than Remembering Why', angle: 'Recording the reasoning so reversals are informed rather than accidental.' },
  { id: 'context-switching-cost', keyword: 'context switching cost', title: 'Measuring What Context Switching Actually Costs You', angle: 'Batching by context rather than by priority, and what that changes.' },
  { id: 'energy-management', keyword: 'founder energy management', title: 'Scheduling Against Energy Instead of Availability', angle: 'Matching the hardest work to the hours it can actually be done in.' },
  { id: 'burnout-early-signals', keyword: 'founder burnout warning signs', title: 'The Operational Signals That Precede Burnout', angle: 'Treating declining decision quality as a leading metric, not a mood.' },
  { id: 'sabbatical-planning', keyword: 'taking time off as a founder', title: 'Making the Business Survivable Without You for Two Weeks', angle: 'A test that doubles as a resilience audit of the whole operation.' },
  { id: 'succession-for-one', keyword: 'business continuity solo operator', title: 'Continuity Planning for a Company of One', angle: 'What has to be documented so the business survives your unavailability.' },
  { id: 'brand-consistency-cheap', keyword: 'brand consistency small business', title: 'Brand Consistency Without a Design Team', angle: 'Constraints — not assets — are what make small-operation output look coherent.' },
  { id: 'naming-things', keyword: 'naming products and features', title: 'Naming Is a Search Problem and a Trademark Problem', angle: 'Checking availability before you fall in love with the name.' },
  { id: 'trademark-basics', keyword: 'trademark basics for founders', title: 'Trademark Reality for Small Operators', angle: 'What registration protects, what it costs, and when it is premature.' },
  { id: 'domain-strategy', keyword: 'domain name strategy', title: 'Domain Strategy: One Brand or a Portfolio', angle: 'Splitting authority across domains is a cost most operators underestimate.' },
  { id: 'redirect-hygiene', keyword: 'managing redirects', title: 'Redirect Chains Are Where Traffic Quietly Disappears', angle: 'Auditing the accumulated layers from every past site restructure.' },
  { id: 'site-migration-checklist', keyword: 'website migration checklist', title: 'Migrating a Site Without Losing the Rankings You Have', angle: 'The pre-flight inventory that determines whether traffic survives.' },
  { id: 'canonical-mistakes', keyword: 'canonical tag mistakes', title: 'Canonical Tags Are Advisory, and That Surprises People', angle: 'Common configurations that send contradictory signals to crawlers.' },
  { id: 'pagination-seo', keyword: 'pagination seo', title: 'Paginated Archives and the Pages Nobody Crawls', angle: 'Making deep content reachable within a sane number of clicks.' },
  { id: 'crawl-budget-reality', keyword: 'crawl budget optimization', title: 'Crawl Budget Only Matters After You Have Wasted It', angle: 'Identifying the generated URLs consuming attention meant for real pages.' },
  { id: 'log-file-analysis', keyword: 'server log analysis seo', title: 'What Server Logs Say That Analytics Cannot', angle: 'Watching what crawlers actually fetch instead of what you submitted.' },
  { id: 'backlink-quality', keyword: 'evaluating backlink quality', title: 'Most Link Building Buys Nothing', angle: 'Distinguishing links that pass real signal from links that pass activity.' },
  { id: 'digital-pr-for-operators', keyword: 'digital pr for small business', title: 'Earning Coverage Without a PR Budget', angle: 'Publishing the data or the tool that gives a journalist a reason to link.' },
  { id: 'original-research', keyword: 'original research content marketing', title: 'Original Data Is the Only Content Nobody Can Copy', angle: 'Finding the dataset you already own and turning it into a citation magnet.' },
  { id: 'case-study-structure', keyword: 'writing a case study', title: 'Case Studies That Survive a Skeptical Reader', angle: 'Naming the constraints and the near-failures, because perfection reads as fiction.' },
  { id: 'testimonial-collection', keyword: 'collecting customer testimonials', title: 'Asking for a Testimonial at the Right Moment', angle: 'Specific prompts produce usable quotes; open requests produce adjectives.' },
  { id: 'objection-handling-content', keyword: 'handling sales objections', title: 'Publish the Answers to the Objections You Keep Getting', angle: 'The page that pre-handles doubt is worth more than the page that pitches.' },
  { id: 'comparison-pages', keyword: 'writing comparison pages', title: 'Comparison Pages That Do Not Insult the Reader', angle: 'Being honest about where the alternative wins is what makes the rest credible.' },
  { id: 'free-tool-strategy', keyword: 'free tool marketing strategy', title: 'The Free Tool as a Distribution Strategy', angle: 'Choosing a tool narrow enough to build and adjacent enough to matter.' },
  { id: 'open-source-as-marketing', keyword: 'open source as marketing', title: 'Open Sourcing Work as a Credibility Instrument', angle: 'What to publish, what to keep, and the maintenance burden you accept.' },
  { id: 'api-as-product', keyword: 'api as a product', title: 'Treating Your API as a Product With Its Own Customers', angle: 'Documentation, versioning, and support expectations as product decisions.' },
  { id: 'integration-partnerships', keyword: 'integration partnerships', title: 'Integrations Are Distribution, If You Pick the Right Partner', angle: 'Evaluating a partner by overlap in customer, not overlap in category.' },
  { id: 'affiliate-program-design', keyword: 'affiliate program design', title: 'Affiliate Programs Attract the Incentives You Design', angle: 'Attribution windows and payout structures determine who shows up.' },
  { id: 'agentic-commerce-readiness', keyword: 'agentic commerce readiness', title: 'Making a Storefront Legible to Shopping Agents', angle: 'Structured product data and machine-readable policies as the new storefront.' },
  { id: 'llm-traffic-shift', keyword: 'llm referral traffic', title: 'What Changes When Answers Arrive Before Clicks', angle: 'Measuring assistant-sourced demand and adapting what you publish.' },
  { id: 'rag-for-support', keyword: 'rag for customer support', title: 'Retrieval-Augmented Support Is a Content Problem First', angle: 'The retrieval quality ceiling is set by documentation you have not written.' },
  { id: 'eval-driven-prompts', keyword: 'evaluating llm outputs', title: 'You Cannot Improve a Prompt You Are Not Grading', angle: 'Building a small evaluation set before iterating on instructions.' },
  { id: 'agent-cost-control', keyword: 'controlling llm api costs', title: 'Agent Costs Scale With Retries, Not Requests', angle: 'Where token spend actually accumulates in a production workflow.' },
  { id: 'human-in-the-loop-design', keyword: 'human in the loop design', title: 'Designing the Review Step So People Actually Review', angle: 'Approval queues degrade into rubber stamps unless the design resists it.' },
];

/** Topics whose keyword collides with an existing indexed page are skipped. */
export function findTopic(id) {
  return archiveTopics.find((topic) => topic.id === id);
}
